#!/usr/bin/env python3
"""Daily Motivation Email pipeline (queue-based).

Reads pre-generated content from data/queue.json, looks up today's entry,
renders Letter (Mon-Fri) or Card (Sat-Sun) HTML template, sends via Gmail SMTP,
and archives markdown to archive/.

Required env vars:
- GMAIL_USER
- GMAIL_APP_PASSWORD
- TO_EMAIL (optional, defaults to GMAIL_USER)

Usage: python3 daily_motivation.py [--dry-run] [--force-date YYYY-MM-DD]

No Anthropic API key needed. The queue is pre-generated by Claude Code.
Refresh monthly by asking Claude Code: "refresh the motivation queue."
"""
import argparse
import json
import os
import smtplib
import ssl
import sys
from datetime import date
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from pathlib import Path

ROOT = Path(__file__).parent
QUEUE_PATH = ROOT / "data" / "queue.json"
TEMPLATES_DIR = ROOT / "templates"
ARCHIVE_DIR = ROOT / "archive"

DAY_COLORS = {
    "Monday":    ("#1E3A5F", "#E8EDF4"),
    "Tuesday":   ("#2D5A3D", "#E8F0EB"),
    "Wednesday": ("#8A4A1C", "#F4ECE3"),
    "Thursday":  ("#B8860B", "#F8F1DD"),
    "Friday":    ("#8B1538", "#F8E5EB"),
    "Saturday":  ("#4B1E6A", "#EDE5F2"),
    "Sunday":    ("#2C2C2C", "#EAEAEA"),
}


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--dry-run", action="store_true", help="Compose but don't send or archive")
    parser.add_argument("--force-date", help="Use this ISO date instead of today (testing)")
    args = parser.parse_args()

    today = args.force_date or date.today().isoformat()
    queue = json.loads(QUEUE_PATH.read_text())

    if today not in queue["emails"]:
        print(f"No queue entry for {today}.", file=sys.stderr)
        print(f"Queue covers through {queue.get('valid_through', 'unknown')}.", file=sys.stderr)
        print("Refresh by asking Claude Code: 'refresh the motivation queue.'", file=sys.stderr)
        return 1

    entry = queue["emails"][today]

    print(f"Today:    {entry['day_name']} {today}")
    print(f"Theme:    {entry['theme']}")
    print(f"Day:      {entry['day_n']}{' [MILESTONE]' if entry['is_milestone'] else ''}")
    print(f"Template: {'Card (weekend)' if entry['is_weekend'] else 'Letter (weekday)'}")
    print(f"Subject:  {entry['subject']}")

    template_name = "card.html" if entry["is_weekend"] else "letter.html"
    template = (TEMPLATES_DIR / template_name).read_text()

    masthead = build_masthead(entry)
    theme_slug = entry["theme"].lower().replace(" / ", "-").replace(" ", "-")
    filename = f"{today}-{entry['day_name'].lower()}-{theme_slug}.md"
    day_color, day_color_tint = DAY_COLORS[entry["day_name"]]

    substitutions = {
        "{{SUBJECT}}":          entry["subject"],
        "{{MASTHEAD}}":         masthead,
        "{{DAY_COLOR}}":        day_color,
        "{{DAY_COLOR_TINT}}":   day_color_tint,
        "{{QUOTE_1}}":          entry["quote_1"],
        "{{QUOTE_2}}":          entry["quote_2"],
        "{{QUOTE_3}}":          entry["quote_3"],
        "{{OPENER_FRAMING}}":   entry["opener_framing"],
        "{{METHOD_FRAMING}}":   entry["method_framing"],
        "{{MINDSET_FRAMING}}":  entry["mindset_framing"],
        "{{ACTION_CALL}}":      entry["action_call"],
        "{{CLOSING_PUNCH}}":    entry["closing_punch"],
        "{{SOURCE_TITLES}}":    entry["source_titles_joined"],
        "{{FILENAME}}":         filename,
    }
    html = template
    for k, v in substitutions.items():
        html = html.replace(k, v)

    plain = build_plain(entry, filename)
    md = build_markdown(entry, today)

    if args.dry_run:
        print("\n=== DRY RUN ===")
        print("\n--- HTML (first 600 chars) ---")
        print(html[:600])
        print("\n--- Plain body ---")
        print(plain)
        print("\n--- Archive markdown ---")
        print(md)
        return 0

    user = os.environ["GMAIL_USER"]
    password = os.environ["GMAIL_APP_PASSWORD"]
    to_addr = os.environ.get("TO_EMAIL", user)

    msg = MIMEMultipart("alternative")
    msg["Subject"] = entry["subject"]
    msg["From"] = user
    msg["To"] = to_addr
    msg.attach(MIMEText(plain, "plain"))
    msg.attach(MIMEText(html, "html"))

    print("Sending via Gmail SMTP...")
    ctx = ssl.create_default_context()
    with smtplib.SMTP("smtp.gmail.com", 587) as server:
        server.starttls(context=ctx)
        server.login(user, password)
        server.sendmail(user, [to_addr], msg.as_string())
    print("  -> sent")

    ARCHIVE_DIR.mkdir(exist_ok=True)
    archive_path = ARCHIVE_DIR / filename
    archive_path.write_text(md)
    print(f"  -> archived {archive_path}")
    return 0


def build_masthead(entry: dict) -> str:
    day_name = entry["day_name"]
    day_n = entry["day_n"]
    is_milestone = entry["is_milestone"]
    iso_date = entry["iso_date"]

    d = date.fromisoformat(iso_date)
    formatted = d.strftime("%B %-d, %Y")

    if entry["is_weekend"]:
        masthead = f"{day_name[:3].upper()} · {formatted.upper()}"
        if is_milestone:
            masthead += f" · DAY {day_n} OF PRACTICE"
    else:
        masthead = f"{day_name} · {formatted}"
        if is_milestone:
            masthead += f" · Day {day_n} of practice"
    return masthead


def build_plain(e: dict, filename: str) -> str:
    return (
        f'> "{e["quote_1"]}"\n\n'
        f'{e["opener_framing"]}\n\n'
        f'**The method.**\n\n'
        f'> "{e["quote_2"]}"\n\n'
        f'{e["method_framing"]}\n\n'
        f'**The mindset.**\n\n'
        f'> "{e["quote_3"]}"\n\n'
        f'{e["mindset_framing"]}\n\n'
        f'**Today\'s call.**\n\n'
        f'{e["action_call"]}\n\n'
        f'{e["closing_punch"]}\n\n'
        f'---\n\n'
        f'Sources: {e["source_titles_joined"]} · Weekly Motivation\n'
        f'Archive: archive/{filename}\n'
    )


def build_markdown(e: dict, today: str) -> str:
    return (
        f'# {e["day_name"]} {today} · {e["theme"]}\n\n'
        f'> "{e["quote_1"]}"\n\n'
        f'{e["opener_framing"]}\n\n'
        f'## The method\n\n'
        f'> "{e["quote_2"]}"\n\n'
        f'{e["method_framing"]}\n\n'
        f'## The mindset\n\n'
        f'> "{e["quote_3"]}"\n\n'
        f'{e["mindset_framing"]}\n\n'
        f'## Today\'s call\n\n'
        f'{e["action_call"]}\n\n'
        f'{e["closing_punch"]}\n\n'
        f'---\n\n'
        f'**Sources:** {e["source_titles_joined"]} · Weekly Motivation notebook\n'
    )


if __name__ == "__main__":
    sys.exit(main())
